name: Build Windows EXE

on:
  push:
    branches: [ main ]  # 只在 main 分支推送时触发
  workflow_dispatch:    # 允许手动触发

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 安装 PyInstaller
      - name: Install PyInstaller
        run: pip install pyinstaller

      # 4. 打包为单文件 EXE
      - name: Build EXE
        run: pyinstaller --onefile --clean pdf.py

      # 5. 上传生成的 EXE 文件
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: YourApp.exe
          path: dist/pdf.exe
